version: '3'
services:

  portainer:
    image: portainer/portainer:linux-arm@sha256:7aa9d50dfebcc84a356c29ec8fb205a7d20b9f2ebbc265b992891c20283b50fd
    container_name: portainer
    command: ["--host=unix:///var/run/docker.sock", "--no-auth"]
    restart: always
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  watchtower:
    image: v2tec/watchtower:armhf-latestsha256:63abf3fc71a46b8fc46674342766d976e6a97d6c70d2560a0986ec63c1784812
    container_name: watchtower
    command: ["--cleanup"]
    restart: on-failure
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  dashboard:
    image: duckietown/dt-duckiebot-dashboard@sha256:247f74be1051c3097dcbbb06a09d9ecbc877a42a5fda40fb7c290731ed69a800
    container_name: duckiebot-dashboard
    restart: always
    network_mode: "host"
    volumes:
      - compose-data:/var/www/html
      # cloud-init userdata file
      - /boot/user-data:/robot/boot/user-data
      # raspberry configuration
      - /boot/config.txt:/robot/boot/config.txt
      # info about the underlying OS (read-only)
      - /boot/os-release:/robot/boot/os-release:ro
      # stuff written by init_sd_card
      - /var/local:/robot/var/local
      # generic duckietown data
      - /data:/robot/data
      # avahi services
      - /etc/avahi/services:/etc/avahi/services
      # docker socket
      - /var/run/docker.sock:/var/run/docker.sock

  dt-device-loader:
    image: duckietown/dt-device-loader:daffy-arm32v7@sha256:82cdea83a565e531b7ad6cdddeccf0265d881e1461ad5e454bad567a45bf6cce
    container_name: device-loader
    restart: on-failure
    network_mode: "host"
    environment:
      - EXCLUDE_RUN=DT18_00_basic
    volumes:
      # docker socket
      - /var/run/docker.sock:/var/run/docker.sock
      # avahi services
      - /etc/avahi/services:/etc/avahi/services
      # duckietown data
      - /data:/data
      - /secrets:/secrets
      - /var/local:/var/local

volumes:
  compose-data:
