version: '3'
services:

  duckietown-swarm:
    image: duckietown/duckietown-swarm-rpi@sha256:817a270459b28fe211ba376c64bae846c170b84d265e5326ce7c6b97978a2946
    restart: unless-stopped
    network_mode: host
    environment:
      DISABLE_CONTRACTS: 1
    volumes:
      - ipfs-storage:/ipfs-storage
    command: dt-swarm daemon --low-power --ipfs-dir /ipfs-storage

volumes:
  ipfs-storage:
