version: '3'
services:

  camera:
    image: duckietown/rpi-duckiebot-ros-picam:master18
    container_name: duckiebot-ros-picam
    restart: unless-stopped
    network_mode: host
    devices:
      - /dev/vchiq:/dev/vchiq
    environment:
      DISABLE_CONTRACTS: 1
    volumes:
      # avahi services
      - /etc/avahi/services:/etc/avahi/services

  video_server:
    image: duckietown/rpi-duckiebot-web_video_server:master18
    container_name: duckiebot-web_video_server
    restart: unless-stopped
    network_mode: host
    volumes:
      # avahi services
      - /etc/avahi/services:/etc/avahi/services
