version: '3'
services:
    duckiebot-interface:
        image: duckietown/duckiebot-interface:master19
        restart: unless-stopped
        network_mode: host
        privileged: true
        environment:
            DISABLE_CONTRACTS: 1
        volumes:
        - /data:/data
