version: '3'
services:

  rpi-simple-server:
    image: duckietown/rpi-simple-server:master18@sha256:6b6787319cd87b413d5b0a8737f6127c719293c12936c94b5ea3a2d7fd62f6b5
    restart: always
    network_mode: "host"
    volumes:
    - "/data:/data"
    working_dir: /data

  rpi-health:
    image: duckietown/rpi-health:master18@sha256:c368e18f3fd804d2b801a6a650a8811f82cd92272a77838737527795aedd79f3
    network_mode: "host"
    devices:
    - "/dev/vchiq:/dev/vchiq"

  rpi-duckiebot-online:
    image: duckietown/rpi-duckiebot-online:master18@sha256:68e5d5b1d6677e8f0110b4f81bb1fb3d47d5658d8de8988108999b7cd8dce3e2
    restart: always
    network_mode: "host"
    volumes:
    - "/data:/data"
    - "/secrets:/secrets"
    - "/var/local:/var/local"

  rpi-duckiebot-loader:
    image: duckietown/rpi-duckiebot-loader:master18@sha256:986708fcac2f9051b17f51c02514279a42089e758b220311ac2de52aa5bad1ec
    restart: always
    network_mode: "host"
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/data:/data"
    - "/secrets:/secrets"
    - "/var/local:/var/local"

